[
  {
    mealId: 99261,
    mealTitle: "Coca Cola - 250ml",
    mealCategory: "Drinks",
    mealThumb: "https://i.ibb.co/LxwRvwG/coca-cola-glass.jpg",
    mealThumbSmall: "",
    mealPrice: 25,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99262,
    mealTitle: "Pepsi - 250ml",
    mealCategory: "Drinks",
    mealThumb: "https://i.ibb.co/JQZfd4c/pepsi.jpg",
    mealThumbSmall: "",
    mealPrice: 25,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99263,
    mealTitle: "Sprite - 250ml",
    mealCategory: "Drinks",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 25,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99264,
    mealTitle: "Seven Up - 250ml",
    mealCategory: "Drinks",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 25,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99266,
    mealTitle: "Sweet Lassi",
    mealCategory: "Drinks",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 100,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99267,
    mealTitle: "Sweet and Sour Lassi",
    mealCategory: "Drinks",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 100,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99268,
    mealTitle: "Mint lime",
    mealCategory: "Drinks",
    mealThumb: "https://i.ibb.co/ZcnDjRw/mint-lemon.jpg",
    mealThumbSmall: "",
    mealPrice: 125,
    mealQuantity: null,
    mealTags: [""],
  },

  {
    mealId: 99271,
    mealTitle: "Cappuccino Coffee",
    mealCategory: "Drinks",
    mealThumb: "https://i.ibb.co/nDMgtbh/cuppuccino-coffee.jpg",
    mealThumbSmall: "",
    mealPrice: 200,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99272,
    mealTitle: "Latte Coffee",
    mealCategory: "Drinks",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 200,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99273,
    mealTitle: "Chocolate Cold Coffee",
    mealCategory: "Drinks",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 175,
    mealQuantity: null,
    mealTags: [""],
  },
];
