const meals = [
  {
    mealId: 99241,
    mealTitle: "Chicken Fried Rice",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 200,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99242,
    mealTitle: "Vegetable Fried Rice",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 175,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99243,
    mealTitle: "Egg Fried Rice",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 175,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99244,
    mealTitle: "Prawn Fried Rice",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99245,
    mealTitle: "Beef Fried Rice",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99246,
    mealTitle: "Steamed Basmati Rice",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 100,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99247,
    mealTitle: "Plain Pulao",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 150,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99251,
    mealTitle: "Chicken Chowmein",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 200,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99252,
    mealTitle: "Szechuan Chowmein",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99253,
    mealTitle: "Prawn Chowmein",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99254,
    mealTitle: "Mixed Chowmein",
    mealCategory: "Rice and Noodles",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [],
  },
];
