const meals = [
  {
    mealId: 99141,
    mealTitle: "Chicken Cashewnut Salad",
    mealCategory: "Salad",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 350,
    mealQuantity: null,
    mealTags: ["popular"],
  },
  {
    mealId: 99142,
    mealTitle: "Grilled Chicken Salad",
    mealCategory: "Salad",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 300,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99143,
    mealTitle: "Thai Shrimp Salad",
    mealCategory: "Salad",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 350,
    mealQuantity: null,
    mealTags: [],
  },
  {
    mealId: 99143,
    mealTitle: "Szechuan Chicken Salad",
    mealCategory: "Salad",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 350,
    mealQuantity: null,
    mealTags: [],
  },
];
