[
  {
    mealId: 99161,
    mealTitle: "Thai Tom Yum Soup",
    mealCategory: "Soup",
    mealThumb: "https://i.ibb.co/F4LKp4b/tom-yum.jpg",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: ["popular"],
  },
  {
    mealId: 99162,
    mealTitle: "Thai Mixed Vegetable Soup",
    mealCategory: "Soup",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99163,
    mealTitle: "Chicken Vegetable Soup",
    mealCategory: "Soup",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99164,
    mealTitle: "Chicken Corn Soup",
    mealCategory: "Soup",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 250,
    mealQuantity: null,
    mealTags: [""],
  },
  {
    mealId: 99165,
    mealTitle: "Special Corn Soup",
    mealCategory: "Soup",
    mealThumb: "",
    mealThumbSmall: "",
    mealPrice: 200,
    mealQuantity: null,
    mealTags: [""],
  },
];
